export const SECONDS_IN_MINUTE = 60
export const MINUTES_IN_HOUR = 60
export const HOURS_IN_DAY = 24
export const DAYS_IN_WEEK = 7
export const MONTHS_IN_YEAR = 12

// MILLISECONDS
export const MILLISECONDS_IN_SECOND = 1000

// SECONDS
export const SECONDS_IN_HOUR = SECONDS_IN_MINUTE * MINUTES_IN_HOUR
export const SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_IN_DAY